name: 'Puppeteer Action'
description: 'Take and save a Puppeteer screenshot with a customizable name, and update the latest image'
branding:
  icon: 'camera'
  color: 'purple'
inputs:
  url:
    description: 'The URL to visit and screenshot'
    required: true
  folder:
    description: 'The folder to save screenshots in'
    required: true
    default: 'timeline'
  basename:
    description: 'The base name for the screenshot (e.g., "screenshot")'
    required: true
    default: 'screenshot'
  make_video:
    description: 'Whether to generate a video timeline from screenshots'
    required: false
    default: 'false'
  video_name:
    description: 'Output video name (e.g., "timeline.mp4")'
    required: false
    default: 'timeline.mp4'
  frame_duration:
    description: 'How long (seconds) each image should display in the video'
    required: false
    default: '1'
  scale_width:
    description: 'Width of output video in pixels (height auto-scaled)'
    required: false
    default: '640'

runs:
  using: 'docker'
  image: 'Dockerfile'
